theme: jekyll-theme-cayman
title: Persson Group Handbook
description: The Persson Group Handbook. Contains useful information for new students and post-docs.
show_downloads: false


# Tipue search settings
tipue_search:
  include:
    pages: true
  exclude:
    files: [search.html]

tipue_search_active: true

markdown_extensions:
 - markdown_fenced_code_tabs
